version: '3'
services:
  blog-api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/blog
    restart: always
    ports:
      - "1717:1717"
    command: bash /app/mongo-seed/wait-for-it.sh mongodb:27017 -- mongoimport --db blog --collection users --file seed.json && node build/server.js
  mongodb:
    image: mongo:latest
    restart: always
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    command: bash /wait-for-it.sh mongodb:27017 -- mongoimport --host mongodb --db blog --collection users --type json --file /seed.json --jsonArray
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
