// user
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const TOKEN_FROM_COOKIE = 'TOKEN_FROM_COOKIE';
export const SIGNUP = 'SIGNUP';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

// posts
export const SINGLEPOST = 'SINGLEPOST';
export const RECEIVE_ALL_POSTS = 'RECEIVE_ALL_POSTS';
export const REQUEST_ALL_POSTS = 'REQUEST_ALL_POSTS';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const POST_COMMENT = 'POST_COMMENT';
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST';

// admin
export const RECEIVE_SUBMIT_POST = 'RECEIVE_SUBMIT_POST';
export const REQUEST_SUBMIT_POST = 'REQUEST_SUBMIT_POST';

// snackbar
export const DISPLAY_MESSAGE = 'DISPLAY_MESSAGE';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
